build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.19
  amd64: ghcr.io/home-assistant/amd64-base:3.19
  armv7: ghcr.io/home-assistant/armv7-base:3.19
  armhf: ghcr.io/home-assistant/armhf-base:3.19

args:
  RUBY_VERSION: "3.3.0"
  BUNDLER_VERSION: "2.5.0"
  SILO_VERSION: "main"

labels:
  org.opencontainers.image.title: Silo Feed Reader
  org.opencontainers.image.description: Self-hosted RSS/Atom feed reader with AI-powered daily briefs
  org.opencontainers.image.source: https://github.com/kebabmane/silo-hass-addon
  org.opencontainers.image.licenses: Apache-2.0
  io.hass.type: addon
  io.hass.name: Silo Feed Reader
